# Современные методы анализа данных и машинного обучения, БИ

## НИУ ВШЭ, 2023-24 учебный год

### Домашнее задание №1. Библиотеки Numpy & Pandas

Задание выполнил(а):

Чиркова Юлия

### Общая информация

__Дата выдачи:__ 09.02.2024

__Дедлайн:__ 04:00 19.02.2024

### Оценивание и штрафы

Каждая задача первого раздела (Numpy) оценивается в 2 балла.

Оценка за первый раздел вычисляется по следующей формуле:

$$
s_{\text{numpy}} \times 1/2 ,
$$

где $s_{\text{numpy}}$  — количество баллов, которое вы набрали в сумме по задачам первого раздела.

Каждая задача второго раздела (Pandas) оценивается в 3 балла.

Оценка за второй раздел вычисляется по следующей формуле:

$$
s_{\text{pandas}} \times 10/54 ,
$$

где $s_{\text{pandas}}$  — количество баллов, которое вы набрали в сумме по задачам второго раздела.

Общая оценка за ДЗ вычисляется по следующей формуле:

$$
O_{1} \times 3/10 + O_2 \times 7/10 ,
$$

где $O_1, O_2$  — оценки за первый и второй раздел соответственно.

За сдачу задания позже срока на итоговую оценку за задание накладывается штраф в размере 1 **вторичный** балл в день, но  задержка не может быть больше недели.

**Важно:** В этом домашнем задании предусмотрено несколько заданий, за которые можно получить бонусные баллы. Бонусные баллы прибавляются к обычным баллам, и может выйти так, что ваша итоговая оценка станет больше 10. В таком случае именно это и будет являться вашей оценкой. То есть за это ДЗ **можно** получить больше 10

__Внимание!__ Домашнее задание выполняется самостоятельно. «Похожие» решения считаются плагиатом и все задействованные студенты (в том числе те, у кого списали) не могут получить за него больше 0 баллов.

### Формат сдачи

Загрузка файлов с решениями происходит в системе [Anytask](https://anytask.org/). Необходимо загружать файл с расширением .ipynb (питоновский ноутбук)

Инвайт для подключения к странице курса в системе — будет указан для каждой группы в нашем телеграмм-канале

## Раздел 1. Numpy

### О задании

В данном разделе вы попрактикуетесь в работе с библиотекой numpy!

In [2]:
import numpy as np

Во всех задачах необходимо написать код решения внутри функции и проверить его работу, вызвав функцию для данных из условия.

При решении задач запрещается использовать циклы (`for`, `while`) и оператор `if`.

Везде, где встречаются массивы или матрицы, подразумевается, что это `numpy.array`.

### 1

Напишите функцию, возвращающую округленную взвешенную сумму оценок по данным оценкам и весам. Можете посчитать свою оценку за курс :) В нашем случае вес экзамена равен 0.32, вес домашек - 0.28, вес групповых проектов - 0.12, вес аудиторки - 0.14, вес контрольной - 0.14. Например, если экзамен написан на 6, домашки сданы на 9, проекты закрыты на 8, оценка за аудиторку 7, а контрольная написана на 10 - итоговая оценка будет хорошо - 7

In [3]:
def result_mark(weights, marks):
    return np.rint(np.sum(weights * marks)).astype(int)

In [4]:
weights = np.array([0.32, 0.18, 0.12, 0.14, 0.14])
marks = np.array([6, 9, 8, 7, 10])
result_mark(weights, marks)

7

### 2

Напишите функцию, меняющую каждое третье (начиная с 0) значение массива целых чисел на заданное число. Например, если на вход поступает массив `array([3, 5, 1, 0, -3, 22, 213436])` и число `-111`, то на выходе должен получиться массив `array([-111, 5, 1, -111, -3, 22, -111])`.

In [5]:
def change_array(array, number):
    array[::3] = number
    return array

In [6]:
array = np.array([3, 5, 1, 0, -3, 22, 213436])
number = -111
change_array(array, number)

array([-111,    5,    1, -111,   -3,   22, -111])

### 3

Напишите функцию, выдающую индексы «близких» элементов заданных массивов, а именно тех пар элементов, чей модуль разницы не превосходит заданного значения. Например, если на вход поступают массив `array([1.5, 0.5, 2, -4.1, -3, 6, -1])`, массив `array([1.2, 0.5, 1, -4, 3, 0, -1.2])` и число `0.5`, то на выходе должен получиться массив `array([0, 1, 3, 6])` (_**важно: не `tuple`, а одномерный массив типа `numpy.ndarray` (то есть `.ndim` от него равно 1)!**_).

In [7]:
def find_close(array1, array2, precision):
    array = np.abs(array1-array2)
    return np.arange(len(array))[array <= precision]

In [8]:
array1 = np.array([1.5, 0.5, 2, -4.1, -3, 6, -1])
array2 = np.array([1.2, 0.5, 1, -4, 3, 0, -1.2])
precision = 0.5
find_close(array1, array2, precision)

array([0, 1, 3, 6])

### 4

Напишите функцию, которая составляет блочную матрицу из четырех блоков, где каждый блок - это заданная матрица. Например, если на вход поступает матрица
$$
\begin{pmatrix}
0 & 1 & 2\\
3 & 4 & 5\\
\end{pmatrix},
$$
то ответом будет матрица
$$
\begin{pmatrix}
0 & 1 & 2 & 0 & 1 & 2\\
3 & 4 & 5 & 3 & 4 & 5\\
0 & 1 & 2 & 0 & 1 & 2\\
3 & 4 & 5 & 3 & 4 & 5\\
\end{pmatrix}
$$

In [9]:
def block_matrix(block):
    return np.vstack((np.hstack((block, block)), np.hstack((block, block))))

In [10]:
block = np.array([[0, 1, 2], [3, 4, 5]])
block_matrix(block)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

### 5

Напишите функцию, вычисляющую произведение всех ненулевых диагональных элементов на диагонали данной квадратной матрицы. Например, если на вход поступает матрица
$$
\begin{pmatrix}
0 & 1 & 2\\
3 & 4 & 5\\
6 & 7 & 8\\
\end{pmatrix},
$$
то ответом будет 32.

In [11]:
def diag_prod(matrix):
    return matrix.diagonal()[matrix.diagonal() != 0].prod()

In [12]:
matrix = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
diag_prod(matrix)

32

### 6

Для улучшения качества работы некоторых алгоритмов машинного обучения может быть полезно использовать [нормализацию данных](https://vk.cc/8xmfQk), чтобы привести признаки в выборке к одному масштабу — а именно, из каждого столбца вычесть среднее его значений и поделить на их стандартное отклонение. Напишите функцию, нормализующую входящую матрицу (по столбцам). Например, если на вход подается матрица
$$
\begin{pmatrix}
1 & 4 & 4200\\
0 & 10 & 5000\\
1 & 2 & 1000\\
\end{pmatrix},
$$
то результатом с точностью до сотых будет матрица
$$
\begin{pmatrix}
0.71 & -0.39 & 0.46\\
-1.41 & 1.37 & 0.93\\
0.71 & -0.98 & -1.39\\
\end{pmatrix}
$$

_Подсказка. Учтите, что в вашей матрице не должно получаться никаких nan. Подумайте, в каком случае они могут возникнуть и как обойти эту проблему._

In [13]:
def normalize(matrix):
    difference = matrix - np.mean(matrix, axis = 0)
    res = np.round(np.divide(difference, np.std(matrix, axis = 0), out = difference, where = np.std(matrix, axis = 0) != 0), 2)
    return res

In [14]:
matrix = np.array([[1, 4, 4200], [0, 10, 5000], [1, 2, 1000]])
normalize(matrix)

array([[ 0.71, -0.39,  0.46],
       [-1.41,  1.37,  0.93],
       [ 0.71, -0.98, -1.39]])

### 7

Напишите функцию, вычисляющую какую-нибудь первообразную данного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$.

In [15]:
def antiderivative(coefs):
    ans = np.polyint(coefs)
    ans[-1] = 7
    return ans

In [16]:
coefs = np.array([4, 6, 0, 1])
antiderivative(coefs)

array([1., 2., 0., 1., 7.])

### 8

Напишите функцию, делающую данную [треугольную матрицу](https://ru.wikipedia.org/wiki/%D0%A2%D1%80%D0%B5%D1%83%D0%B3%D0%BE%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86%D0%B0) симметричной. Например, если на вход поступает матрица
$$
\begin{pmatrix}
1 & 2 & 3 & 4\\
0 & 5 & 6 & 7\\
0 & 0 & 8 & 9\\
0 & 0 & 0 & 10\\
\end{pmatrix},
$$
то на выходе должна быть матрица
$$
\begin{pmatrix}
1 & 2 & 3 & 4\\
2 & 5 & 6 & 7\\
3 & 6 & 8 & 9\\
4 & 7 & 9 & 10\\
\end{pmatrix}.
$$

In [17]:
def make_symmetric(matrix):
    matrix_T = np.copy(np.transpose(matrix))
    np.fill_diagonal(matrix_T, 0)
    return matrix + matrix_T

In [18]:
matrix = np.array([[1, 2, 3, 4], [0, 5, 6, 7], [0, 0, 8, 9], [0, 0, 0, 10]])
make_symmetric(matrix)

array([[ 1,  2,  3,  4],
       [ 2,  5,  6,  7],
       [ 3,  6,  8,  9],
       [ 4,  7,  9, 10]])

### 9

Напишите функцию, создающую прямоугольную матрицу из m одинаковых строк, заполненных последовательными натуральными числами от a до b включительно в возрастающем порядке. Например, если m = 5, a = 3, b = 10, то на выходе будет матрица
$$
\begin{pmatrix}
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
\end{pmatrix}
$$

In [19]:
def construct_matrix(m, a, b):
    return np.zeros((m, b - a + 1)) + np.arange(a, b + 1)

In [20]:
m = 5
a = 3
b = 10
construct_matrix(m, a, b)

array([[ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

### 10

Напишите функцию, вычисляющую [косинусную близость](https://en.wikipedia.org/wiki/Cosine_similarity) двух векторов. Например, если на вход поступают вектора `array([-2, 1, 0, -5, 4, 3, -3])` и `array([0, 2, -2, 10, 6, 0, 0])`, ответом будет -0.25.

In [21]:
def cosine_similarity(vec1, vec2):
    a = vec1 * vec2
    return a.sum() / (np.linalg.norm(vec1) * np.linalg.norm(vec2))

In [22]:
vec1 = np.array([-2, 1, 0, -5, 4, 3, -3])
vec2 = np.array([0, 2, -2, 10, 6, 0, 0])
cosine_similarity(vec1, vec2)

-0.25

## Раздел 2. Pandas

### О задании

В данном разделе вы попрактикуетесь в работе с библиотекой pandas!

In [23]:
import pandas as pd

Обратите внимание, что практически во всех заданиях вам потребуется написать какой-то текст в виде вывода/результата/итога/какого-то резюме. Пожалуйста, не ленитесь, и пишите выводы ***подробно***, существенная часть баллов будет выставляться именно за выводы, так как в анализе данных они имеют большое значение. Таким образом, на любое задание, сформулированное в виде вопроса, отвечайте текстом, подкрепляя ваши слова написанным и выполненным кодом. Текст выводов/комментариев пишите в отдельных ячейках, используя средства текстового редактора Jupyter Notebook/Google Colab, при необходимости используйте средства *выделения*.

При решении задач, когда вам необходимо сделать какой-то фильтр, срез, выборку, или иное действие с данными, запрещается использовать циклы (`for`, `while`) и оператор `if`.

### 1

В этом разделе домашнего задания вы поработаете с данными исследования зависимости средней продолжительности жизни по странам от количества употребляемого в стране алкоголя.

Вашему вниманию представлено два датасета: drinks.csv и lifeexpectancy-verbose.csv

Первая таблица содержит в себе сводные данные по количеству употребляемого алкоголя в каждой стране.

Описание датасета:
- country -	Name of the country (String)
- beer_servings	- Number of beer servings per person in the country (Integer)
- spirit_servings	- Number of spirit servings per person in the country (Integer)
- wine_servings	- Number of wine servings per person in the country(Integer)
- total_litres_of_pure_alcohol -	Total litres of pure alcohol consumed per person in the country (Float)

Вторая таблица содержит в себе информацию о научных статьях и исследованиях о продолжительности жизни (в разных категориях и для разных групп) по той или иной стране.

Откройте в ноутбуке оба файла с данными. Какой размер имеют таблицы? Выведите первые 5 и последние 5 строк для обеих таблиц. Сколько уникальных стран представлено в каждой из таблиц? Сделайте выводы.

Подгрузила данные напрямую в колаб, со ссылкой на гитхаб не прокатило

In [24]:
drink = pd.read_csv('drinks.csv')
drink.head() #первые 5 строк датасета о потреблении алкоголя

,index,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
0,0,Afghanistan,0,0,0,0.0
1,1,Albania,89,132,54,4.9
2,2,Algeria,25,0,14,0.7
3,3,Andorra,245,138,312,12.4
4,4,Angola,217,57,45,5.9

In [25]:
drink.tail() #последние 5 строк датасета о потреблении

,index,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
188,188,Venezuela,333,100,3,7.7
189,189,Vietnam,111,2,1,2.0
190,190,Yemen,6,0,0,0.1
191,191,Zambia,32,19,4,2.5
192,192,Zimbabwe,64,18,4,4.7

In [26]:
print(drink.shape, 'размер датасета с напитками')

(193, 6) размер датасета с напитками

In [27]:
lifeexp = pd.read_csv('lifeexpectancy-verbose.csv')
lifeexp.head() #вывод первых 5 строк датасета о продолжительности жизни

,index,GhoCode,GhoDisplay,PublishStateCode,PublishStateDisplay,YearCode,YearDisplay,RegionCode,RegionDisplay,WorldBankIncomeGroupGroupCode,WorldBankIncomeGroupDisplay,CountryCode,CountryDisplay,SexCode,SexDisplay,DisplayValue,Numeric
0,0,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,1990,1990,AMR,Americas,WB_LMI,Lower_middle_income,NIC,Nicaragua,MLE,Male,68,68.0
1,1,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),PUBLISHED,Published,2012,2012,EUR,Europe,WB_HI,High_income,IRL,Ireland,MLE,Male,69,69.3
2,2,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,2000,2000,EMR,Eastern Mediterranean,WB_LI,Low_income,YEM,Yemen,BTSX,Both sexes,61,61.0
3,3,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,2000,2000,AFR,Africa,WB_LMI,Lower_middle_income,NGA,Nigeria,FMLE,Female,48,48.0
4,4,WHOSIS_000015,Life expectancy at age 60 (years),PUBLISHED,Published,1990,1990,SEAR,South_East Asia,WB_LMI,Lower_middle_income,THA,Thailand,FMLE,Female,19,19.0

In [28]:
lifeexp.tail() #вывод последних 5 строк датасета о продолжительности жизни

,index,GhoCode,GhoDisplay,PublishStateCode,PublishStateDisplay,YearCode,YearDisplay,RegionCode,RegionDisplay,WorldBankIncomeGroupGroupCode,WorldBankIncomeGroupDisplay,CountryCode,CountryDisplay,SexCode,SexDisplay,DisplayValue,Numeric
6403,6403,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,2000,2000,EMR,Eastern Mediterranean,WB_LMI,Lower_middle_income,MAR,Morocco,BTSX,Both sexes,68,68.00000
6404,6404,WHOSIS_000015,Life expectancy at age 60 (years),PUBLISHED,Published,1990,1990,WPR,Western Pacific,WB_UMI,Upper_middle_income,PLW,Palau,BTSX,Both sexes,16,16.00000
6405,6405,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,1990,1990,AFR,Africa,WB_LI,Low_income,BFA,Burkina Faso,FMLE,Female,51,51.00000
6406,6406,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),PUBLISHED,Published,2012,2012,EUR,Europe,WB_LMI,Lower_middle_income,ALB,Albania,MLE,Male,64,63.50000
6407,6407,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,2013,2013,EUR,Europe,NaN,NaN,ARM,Armenia,BTSX,Both sexes,71,71.02699

In [29]:
print(lifeexp.shape, 'размер датасета с аналитикой продолжительности жизни')

(6408, 17) размер датасета с аналитикой продолжительности жизни

In [30]:
drink.country.nunique()

193

In [31]:
lifeexp.CountryDisplay.nunique()

194

В датасете с напитками на 1 страну меньше, чем в датасете с аналитикой продолжительности жизни. Скорее всего, при их совмещении, статистика по одной из стран пропадет.

### 2

Для каждого признака в рассматриваемых данных укажите тип этого признака и кратко обоснуйте, почему тип именно такой.

Посмотрим на то, какие типы в каждой из колонок присутствуют для более простого определения данных

In [32]:
drink.dtypes

index                             int64
country                          object
beer_servings                     int64
spirit_servings                   int64
wine_servings                     int64
total_litres_of_pure_alcohol    float64
dtype: object

In [33]:
lifeexp.dtypes

index                              int64
GhoCode                           object
GhoDisplay                        object
PublishStateCode                  object
PublishStateDisplay               object
YearCode                           int64
YearDisplay                        int64
RegionCode                        object
RegionDisplay                     object
WorldBankIncomeGroupGroupCode     object
WorldBankIncomeGroupDisplay       object
CountryCode                       object
CountryDisplay                    object
SexCode                           object
SexDisplay                        object
DisplayValue                       int64
Numeric                          float64
dtype: object

Количество уникальных значений по каждому из столбцов

In [34]:
[drink.beer_servings.nunique(), drink.spirit_servings.nunique(),
 drink.wine_servings.nunique(), drink.total_litres_of_pure_alcohol.nunique()]

[130, 109, 79, 90]

In [35]:
[lifeexp.GhoCode.unique(), lifeexp.GhoDisplay.unique()]
#выводим уникальные значения для двух колонок, аналогичные действия будем делать со всеми последующими "парами"

[array(['WHOSIS_000001', 'WHOSIS_000002', 'WHOSIS_000015'], dtype=object),
 array(['Life expectancy at birth (years)',
        'Healthy life expectancy (HALE) at birth (years)',
        'Life expectancy at age 60 (years)'], dtype=object)]

In [36]:
[lifeexp.PublishStateCode.unique(), lifeexp.PublishStateDisplay.unique()]

[array(['PUBLISHED'], dtype=object), array(['Published'], dtype=object)]

In [37]:
[lifeexp.YearCode.unique(), lifeexp.YearDisplay.unique()]

[array([1990, 2012, 2000, 2013]), array([1990, 2012, 2000, 2013])]

In [38]:
[lifeexp.RegionCode.unique(), lifeexp.RegionDisplay.unique()]

[array(['AMR', 'EUR', 'EMR', 'AFR', 'SEAR', 'WPR'], dtype=object),
 array(['Americas', 'Europe', 'Eastern Mediterranean', 'Africa',
        'South_East Asia', 'Western Pacific'], dtype=object)]

In [39]:
[lifeexp.WorldBankIncomeGroupGroupCode.unique(), lifeexp.WorldBankIncomeGroupDisplay.unique()]

[array(['WB_LMI', 'WB_HI', 'WB_LI', 'WB_UMI', nan], dtype=object),
 array(['Lower_middle_income', 'High_income', 'Low_income',
        'Upper_middle_income', nan], dtype=object)]

In [40]:
[lifeexp.CountryCode.nunique(), lifeexp.CountryDisplay.nunique()]

[194, 194]

In [41]:
[lifeexp.SexCode.unique(), lifeexp.SexDisplay.unique()]

[array(['MLE', 'BTSX', 'FMLE'], dtype=object),
 array(['Male', 'Both sexes', 'Female'], dtype=object)]

Посмотрев на значения колонок вида <text>Code, <text>Display, можно сделать вывод, что первая из них является просто кодовым номером (ого да code = код), значением для категорий, представленных в колонке display.

In [42]:
[lifeexp.DisplayValue.nunique(), lifeexp.Numeric.nunique()]

[74, 1567]

**Датасет о количестве употребляемого алкоголя в каждой стране (drinks.csv):**

*   index - вещественный признак, обозначает просто нумерацию в таблице
*   country - категориальный признак, так как является просто перечислением всех стран мира
*   beer_servings, wine_servings, spirit_servings - вещественные признаки, принимают натуральные значения и вероятнее всего обозначают среднее количество порций пива, вина и крепких напитков на страну, принимает разные значения
* total_litres_of_pure_alcohol - вещественный, поскольку обозначает количество выпитого алкоголя в разных странах и может принимать любое вещественное значение

**Датасет о продожительности жизни**

*   index - вещественный признак, обозначает просто нумерацию в таблице
*   GhoCode - категориальный признак, поскольку содержит в себе три типа строковых значений, являющихся кодами для ВОЗ
*   GhoDisplay - категориальный, поскольку содержит в себе три типах строковых значений, описывающих погруппу людей по возрасту/здоровью для измерения продолжительности жизни (например, Life expectancy at age 60 (years) -- средняя продолжительность жизни после 60ти лет)
*   PublishStateCode - унарный??, но вообще категориальный, возможно, исходно бинарный аля published/ not published, где он показывает просто наличие данных
*   PublishStateDisplay - аналогично предыдущему признаку
*   YearCode - вещественный, но я бы сказала именно типа date, поскольку отражает год, в который были собраны данные
*   YearDisplay - аналогично YearCode
*   RegionCode - закодированное название региона, является категориальным признаком, так как нельзя отранжировать
*   RegionDisplay - название региона, является категориальным признаком, его нельзя отранжировать и представлено типом object
*   WorldBankIncomeGroupGroupCode - закодированный тип уровня дохода, порядковый признак, но на данный момент присутствуют и nan значения
*   WorldBankIncomeGroupDisplay - описание типа дохода, порядковый признак, так как можно ранжировать по возрастанию от самого низкого до наиболее высокого типа дохода, строковые значения
*   CountryCode - закодированное название страный, их 194 категории (по кол-ву стран, признанных ООН), категориальный признак
*   CountryDisplay - категориальный признак, показывает название страны, их нельзя ранжировать
*   SexCode - показывает тип рассматриваемых данных (оба пола, женский или мужской), категориальный признак
*   SexDisplay - показывает наименование категории по полу рассматриваемых данных, категориальный признак
*   DisplayValue - натуральное значение, целое значение продолжительности жизни, вещественный признак
*   Numeric - вещественное значение продолжительности жизни, вещественный признак

### 3

Внимательно изучите признаки обеих таблиц. Как вы считаете, какая из таблиц является главной (а какая сопутствующей)? Почему вы так думаете?

Какой признак может представлять существенный интерес для исследования и являться целевой переменной в рамках представленного датасета? Ответ обоснуйте.

***Бонус (1 бон. балл):*** Попробуйте описать задачу машинного обучения, которую вы могли бы решать для данного датасета с учетом выбранной вами раннее целевой переменной и проблематики исследования. Подробнее про постановку и формализацию задач машинного обучения, а также про различные типы таких задач — вы можете прочитать, например, вот в этой [статье](https://habr.com/ru/company/simbirsoft/blog/565396/) (в начале)

Главной является таблица lifeexpectancy-verbose.csv, поскольку в ней есть данные относительно продолжительности жизни в зависимости от совокупности факторов, а также оценка продолжительности жизни является целевой перемеенной. В ней две колокнки с целевыми значениями: Numeric - неокругленная средняя продолжительность жизни, а DisplayValue - округленная.
Таблица drinks.csv является вспомогательной, поскольку в ней содержатся собранные статистические данные, которые нельзя изменить и нет смысла предсказывать.
**Задачи машинного обучения:** задача регрессии для предсказания продолжительности жизни относительно рассматриваемой статьи в последующем году (так как есть данные для 1990, 2000, 2012 и 2013 года) для определенной страны, региона итд.

### 4

Какова доля статей о продолжительности жизни в Африке? Какова доля статей о продолжительности жизни мужчин и доля статей о продолжительности жизни женщин среди всех статей по Африке?

***Бонус (2 бон. балла):*** Сравните эти доли с аналогичными долями по другим регионам. Как вы можете объяснить возникающие сходства и различия? Прокомментируйте полученные результаты.

In [43]:
#доля статей о продолжительности жизни в Африке
lifeexp[lifeexp.RegionDisplay == 'Africa'].shape[0]/lifeexp.shape[0]

0.23782771535580524

In [44]:
#доля статей о продожительности жизни мужчин в Африке среди всех статей по Африке
lifeexp[(lifeexp.RegionDisplay == 'Africa')& (lifeexp.SexDisplay == 'Male')].shape[0]/lifeexp[lifeexp.RegionDisplay == 'Africa'].shape[0]

0.3333333333333333

In [45]:
#доля статей о продожительности жизни женщин в Африке среди всех статей по Африке
lifeexp[(lifeexp.RegionDisplay == 'Africa')& (lifeexp.SexDisplay == 'Female')].shape[0]/lifeexp[lifeexp.RegionDisplay == 'Africa'].shape[0]

0.3333333333333333

In [46]:
def share_male(df):
    return df[df.SexDisplay == 'Male'].shape[0]/df.shape[0]

In [47]:
lifeexp.groupby('RegionDisplay').apply(share_male).to_frame()

                              0
RegionDisplay
Africa                 0.333333
Americas               0.333333
Eastern Mediterranean  0.333333
Europe                 0.333333
South_East Asia        0.333333
Western Pacific        0.333333

In [48]:
def share_female(df):
    return df[df.SexDisplay == 'Female'].shape[0]/df.shape[0]

In [49]:
lifeexp.groupby('RegionDisplay').apply(share_female).to_frame()

                              0
RegionDisplay
Africa                 0.333333
Americas               0.333333
Eastern Mediterranean  0.333333
Europe                 0.333333
South_East Asia        0.333333
Western Pacific        0.333333

 **Вывод**: доля исследований по мужчинам и женщинам по отдельности  1/3 у каждой из групп, является таковой, поскольку для каждой страны были проведены исследования по трем типам групп по полу и всем остальным признакам.

In [50]:
def share(df):
    return df.shape[0]/lifeexp.shape[0]

In [51]:
lifeexp.groupby('RegionDisplay').apply(share).to_frame()

                              0
RegionDisplay
Africa                 0.237828
Americas               0.180243
Eastern Mediterranean  0.113296
Europe                 0.272940
South_East Asia        0.056648
Western Pacific        0.139045

**Вывод**: большая доля в Европе, поскольку в Европе наибольшее количество стран и регионов, по которым могли быть проведены исследования, соответственно из-за разного количества стран и регионов в разных частях мира и были получены различия.

### 5

Сколько всего существует видов статей с точки зрения оцениваемого параметра продолжительности жизни? Какой из этих видов статей самый популярный (написано наибольшее количество научных работ)? В рамках найденного вами самого популярного вида статей проведите сравнение, относительно какой из половых групп: мужчины, женщины или же оба пола — статей в нем было больше всего?

In [52]:
lifeexp['GhoDisplay'].count()

6408

In [53]:
lifeexp.groupby('GhoDisplay')['Numeric'].count()

GhoDisplay
Healthy life expectancy (HALE) at birth (years)    1752
Life expectancy at age 60 (years)                  2328
Life expectancy at birth (years)                   2328
Name: Numeric, dtype: int64

Есть две группы с одинаковым количество научных работ -- продолжительность жизни в возрасте 60ти лет и продолжительность жизни в целом (с начала жизни). Их по 2328.

In [54]:
lifeexp[lifeexp.GhoDisplay == 'Life expectancy at age 60 (years)'].groupby('SexDisplay')['Numeric'].count()

SexDisplay
Both sexes    776
Female        776
Male          776
Name: Numeric, dtype: int64

In [55]:
lifeexp[lifeexp.GhoDisplay == 'Life expectancy at birth (years)'].groupby('SexDisplay')['Numeric'].count()

SexDisplay
Both sexes    776
Female        776
Male          776
Name: Numeric, dtype: int64

**Вывод**: В каждом из рассматриваемых типов научных работ статей по трем из половых групп одинаковое количество.

### 6

Выведите минимальную, среднюю, медианную и максимальную оцененную продолжительность жизни людей от рождения (life expectancy at birth). Выберите любые три страны на ваш вкус и проделайте то же самое только для статей по этим странам. Что можно сказать на основе результатов, которые вы получили?

In [56]:
lifeexp[lifeexp.GhoDisplay == 'Life expectancy at birth (years)'].agg({'Numeric':['min', 'mean','median', 'max'],
                                                                      'DisplayValue':['min', 'mean','median', 'max']})

          Numeric  DisplayValue
min     38.000000     38.000000
mean    68.441379     68.437285
median  70.857895     71.000000
max     87.154570     87.000000

In [57]:
lifeexp[(lifeexp.GhoDisplay == 'Life expectancy at birth (years)') &
        ((lifeexp.CountryDisplay == 'Andorra') | (lifeexp.CountryDisplay == 'Eritrea') |
        (lifeexp.CountryDisplay == 'Myanmar'))
       ].groupby('CountryDisplay').agg({'Numeric':['min', 'mean','median', 'max'],
                                                                      'DisplayValue':['min', 'mean', 'median', 'max']})

               Numeric                                DisplayValue             \
                   min       mean    median       max          min       mean
CountryDisplay
Andorra           74.0  80.576820  80.50000  86.00000           74  80.583333
Eritrea           39.0  55.291194  57.50000  66.31112           39  55.250000
Myanmar           57.0  63.232317  63.99803  68.00000           57  63.250000


               median max
CountryDisplay
Andorra          80.5  86
Eritrea          57.5  66
Myanmar          64.0  68

**Вывод**: Весьма логично, что получили наиболее высокий уровень жизни в Европейской стране, а самые низкие показатели в Эритреи - бедной африканской стране. Помимо этого в Мьянме (довольно бедной азиатской стране) - средний уровень продолжительности жизни.

### 7

Сформируйте результирующий датафрейм на основе проделанных вами действий в предыдущем номере. У датафрейма должно быть 4 столбца, в соответствии с заданными агреггирующими функциями: минимум, среднее, медиана, максимум, — а также 4 строки: статистика по всему датасету; статистика по трем выбранным вами странам. Сохраните программно созданный вами датафрейм в виде csv файла.

*Примечание. Датафрейм необходимо создавать автоматизированным образом. Не допускается ручной перенос значений из полученных в предыдущем задании ячеек в пустой датафрейм и/или прописывание конкретных значений (чисел) в коде программы. Представьте, что у нас не 3 страны, а 100 и не 4 агреггирующих метрики, а 100!*

In [58]:
countries = ['Andorra', 'Eritrea', 'Myanmar']

In [59]:
all = lifeexp[lifeexp.GhoDisplay == 'Life expectancy at birth (years)'].Numeric.agg(
    ['min', 'mean', 'median', 'max']).to_frame().transpose()
all.rename(index={'Numeric': 'All'}, inplace=True)
all

      min       mean     median       max
All  38.0  68.441379  70.857895  87.15457

In [60]:
cstat = lifeexp[(lifeexp.GhoDisplay == 'Life expectancy at birth (years)') &
 (lifeexp.CountryDisplay.isin(countries))].groupby('CountryDisplay').Numeric.agg(
    ['min', 'mean', 'median', 'max'])

cstat

                 min       mean    median       max
CountryDisplay
Andorra         74.0  80.576820  80.50000  86.00000
Eritrea         39.0  55.291194  57.50000  66.31112
Myanmar         57.0  63.232317  63.99803  68.00000

In [61]:
res_stat = pd.concat([cstat, all])
res_stat

          min       mean     median       max
Andorra  74.0  80.576820  80.500000  86.00000
Eritrea  39.0  55.291194  57.500000  66.31112
Myanmar  57.0  63.232317  63.998030  68.00000
All      38.0  68.441379  70.857895  87.15457

In [62]:
res_stat.to_csv('country_statistics.csv')

In [63]:
!ls

country_statistics.csv	drinks.csv  lifeexpectancy-verbose.csv	sample_data

### 8

Есть ли в наших датасетах пропуски? Если да, то в каких столбцах? Сколько пропусков в каждом из них?

Подумайте, как стоит избавиться от пропусков в каждом из столбцов, и сделайте это. Аргументируйте ваши действия.

Проверьте, что пропусков нигде не осталось.

*Примечание. Не забудьте сохранить все изменения! В последующих заданиях вы должны работать с уже обновленными датасетами.*

In [64]:
lifeexp.isna().sum()

index                               0
GhoCode                             0
GhoDisplay                          0
PublishStateCode                    0
PublishStateDisplay                 0
YearCode                            0
YearDisplay                         0
RegionCode                          0
RegionDisplay                       0
WorldBankIncomeGroupGroupCode    1164
WorldBankIncomeGroupDisplay      1164
CountryCode                         0
CountryDisplay                      0
SexCode                             0
SexDisplay                          0
DisplayValue                        0
Numeric                             0
dtype: int64

In [65]:
drink.isna().sum()

index                           0
country                         0
beer_servings                   0
spirit_servings                 0
wine_servings                   0
total_litres_of_pure_alcohol    0
dtype: int64

**Вывод**: В датасете о количестве выпитого алкоголя - нет пропущенных значений, а в датасете о продолжительности жизни по 1164 пропущенных значения в колонках о группе людей по уронвю дохода.

Дальше будет много кода, где я пыталась какого характера пропуски и в каких именно данных они встречаются.

In [66]:
lifeexp.WorldBankIncomeGroupDisplay.isna().groupby([lifeexp.GhoDisplay, lifeexp.YearDisplay]).sum().to_frame()

                                                             WorldBankIncomeGroupDisplay
GhoDisplay                                      YearDisplay
Healthy life expectancy (HALE) at birth (years) 2000                                   0
                                                2012                                   0
                                                2013                                   0
Life expectancy at age 60 (years)               1990                                   0
                                                2000                                   0
                                                2012                                   0
                                                2013                                 582
Life expectancy at birth (years)                1990                                   0
                                                2000                                   0
                                                2012                                   0
                                                2013                                 582

1. Узнали, что все пропуски находятся в двух категориях статей (продолжительность жизни от рождения и продолжительность жизни от 60ти лет), а также в 2013 году.

2. Для более полной картины, попробовала посмотреть, по сколько категорий по уровню дохода было в каждой стране и выяснила, что две (не нановские значения) были только в Южном судане, причем, начиная с 2000 года пишется по три статьи в категории Lower_middle_income и HALE, в зависимости от пола, а все остальные - low income.

In [67]:
df = lifeexp.groupby([lifeexp.CountryDisplay]).agg({'WorldBankIncomeGroupDisplay': 'nunique'})
df.WorldBankIncomeGroupDisplay.unique()

array([1, 2])

In [68]:
df[df.WorldBankIncomeGroupDisplay == 2]

                WorldBankIncomeGroupDisplay
CountryDisplay
South Sudan                               2

In [69]:
lifeexp[lifeexp.CountryDisplay == 'South Sudan'].groupby('YearDisplay').agg(
    {'WorldBankIncomeGroupDisplay': 'unique'})

                   WorldBankIncomeGroupDisplay
YearDisplay
1990                              [Low_income]
2000         [Low_income, Lower_middle_income]
2012         [Low_income, Lower_middle_income]
2013                [Lower_middle_income, nan]

In [70]:
lifeexp[(lifeexp.CountryDisplay == 'South Sudan') & (lifeexp.YearCode == 2000)]

,index,GhoCode,GhoDisplay,PublishStateCode,PublishStateDisplay,YearCode,YearDisplay,RegionCode,RegionDisplay,WorldBankIncomeGroupGroupCode,WorldBankIncomeGroupDisplay,CountryCode,CountryDisplay,SexCode,SexDisplay,DisplayValue,Numeric
1182,1182,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),PUBLISHED,Published,2000,2000,EMR,Eastern Mediterranean,WB_LI,Low_income,SSD,South Sudan,MLE,Male,41,41.0
2189,2189,WHOSIS_000015,Life expectancy at age 60 (years),PUBLISHED,Published,2000,2000,EMR,Eastern Mediterranean,WB_LI,Low_income,SSD,South Sudan,MLE,Male,15,15.0
2351,2351,WHOSIS_000015,Life expectancy at age 60 (years),PUBLISHED,Published,2000,2000,EMR,Eastern Mediterranean,WB_LI,Low_income,SSD,South Sudan,FMLE,Female,16,16.0
2569,2569,WHOSIS_000015,Life expectancy at age 60 (years),PUBLISHED,Published,2000,2000,EMR,Eastern Mediterranean,WB_LI,Low_income,SSD,South Sudan,BTSX,Both sexes,15,15.0
3032,3032,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),PUBLISHED,Published,2000,2000,EMR,Eastern Mediterranean,WB_LMI,Lower_middle_income,SSD,South Sudan,FMLE,Female,42,42.3
3156,3156,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),PUBLISHED,Published,2000,2000,EMR,Eastern Mediterranean,WB_LMI,Lower_middle_income,SSD,South Sudan,MLE,Male,41,41.0
3518,3518,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,2000,2000,EMR,Eastern Mediterranean,WB_LI,Low_income,SSD,South Sudan,BTSX,Both sexes,49,49.0
3825,3825,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),PUBLISHED,Published,2000,2000,EMR,Eastern Mediterranean,WB_LI,Low_income,SSD,South Sudan,FMLE,Female,42,42.0
3952,3952,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),PUBLISHED,Published,2000,2000,EMR,Eastern Mediterranean,WB_LI,Low_income,SSD,South Sudan,BTSX,Both sexes,42,42.0
4603,4603,WHOSIS_000002,Healthy life expectancy (HALE) at birth (years),PUBLISHED,Published,2000,2000,EMR,Eastern Mediterranean,WB_LMI,Lower_middle_income,SSD,South Sudan,BTSX,Both sexes,42,41.6
6010,6010,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,2000,2000,EMR,Eastern Mediterranean,WB_LI,Low_income,SSD,South Sudan,FMLE,Female,50,50.0
6128,6128,WHOSIS_000001,Life expectancy at birth (years),PUBLISHED,Published,2000,2000,EMR,Eastern Mediterranean,WB_LI,Low_income,SSD,South Sudan,MLE,Male,47,47.0

**Вывод**: Поскольку от колонки с кодом уровня дохода (WorldBankIncomeGroupCode) логичнее всего избавиться, так как она дублирует названия в колонке со значениями уровня дохода, то будем заполнять пропуски только в колонке WorldBankIncomeDisplay значениями из предыдущих годов во всех странах, а в Южном Судане поставим низкий уровень дохода.

In [71]:
lifeexp.WorldBankIncomeGroupDisplay.unique()

array(['Lower_middle_income', 'High_income', 'Low_income',
       'Upper_middle_income', nan], dtype=object)

In [72]:
#выделяем страны с разным уровнем дохода в массивы для дальнейшего заполнения пропуском
lm = lifeexp[(lifeexp.YearCode == 2013) &
 (lifeexp.WorldBankIncomeGroupDisplay == 'Lower_middle_income')]['CountryDisplay'].unique()
lm = list(lm)
lm.remove('South Sudan')

In [73]:
h = lifeexp[(lifeexp.YearCode == 2013) &
 (lifeexp.WorldBankIncomeGroupDisplay == 'High_income')]['CountryDisplay'].unique()
h = list(h)

In [74]:
l = lifeexp[(lifeexp.YearCode == 2013) &
 (lifeexp.WorldBankIncomeGroupDisplay == 'Low_income')]['CountryDisplay'].unique()
l = list(l)

In [75]:
um = lifeexp[(lifeexp.YearCode == 2013) &
 (lifeexp.WorldBankIncomeGroupDisplay == 'Upper_middle_income')]['CountryDisplay'].unique()
um = list(um)

In [76]:
lifeexp.loc[(lifeexp['CountryDisplay'].isin(l)),
            'WorldBankIncomeGroupDisplay'] = lifeexp[lifeexp['CountryDisplay'].isin(l)]['WorldBankIncomeGroupDisplay'].fillna(value='Low_income')
lifeexp.loc[(lifeexp['CountryDisplay'].isin(lm)),
            'WorldBankIncomeGroupDisplay'] = lifeexp[lifeexp['CountryDisplay'].isin(lm)]['WorldBankIncomeGroupDisplay'].fillna(value='Lower_middle_income')
lifeexp.loc[(lifeexp['CountryDisplay'].isin(um)),
            'WorldBankIncomeGroupDisplay'] = lifeexp[lifeexp['CountryDisplay'].isin(um)]['WorldBankIncomeGroupDisplay'].fillna(value='Upper_middle_income')
lifeexp.loc[(lifeexp['CountryDisplay'].isin(h)),
            'WorldBankIncomeGroupDisplay'] = lifeexp[lifeexp['CountryDisplay'].isin(h)]['WorldBankIncomeGroupDisplay'].fillna(value='High_income')
lifeexp.loc[(lifeexp['CountryDisplay'] == 'South Sudan'),
            'WorldBankIncomeGroupDisplay'] = lifeexp[lifeexp['CountryDisplay'] == 'South Sudan']['WorldBankIncomeGroupDisplay'].fillna(value='Low_income')

In [77]:
life = lifeexp.drop(columns='WorldBankIncomeGroupGroupCode')

In [78]:
life.isnull().any()

index                          False
GhoCode                        False
GhoDisplay                     False
PublishStateCode               False
PublishStateDisplay            False
YearCode                       False
YearDisplay                    False
RegionCode                     False
RegionDisplay                  False
WorldBankIncomeGroupDisplay    False
CountryCode                    False
CountryDisplay                 False
SexCode                        False
SexDisplay                     False
DisplayValue                   False
Numeric                        False
dtype: bool

Получили, что в обновленном датасете нет пропусков.

### 9

Все ли признаки несут в себе полезную информацию? Почему вы так считаете? Избавьтесь от ненужных столбцов. Свой выбор аргументируйте

*Примечание. Не забудьте сохранить все изменения! В последующих заданиях вы должны работать с уже обновленными датасетами.*

In [79]:
life.columns

Index(['index', 'GhoCode', 'GhoDisplay', 'PublishStateCode',
       'PublishStateDisplay', 'YearCode', 'YearDisplay', 'RegionCode',
       'RegionDisplay', 'WorldBankIncomeGroupDisplay', 'CountryCode',
       'CountryDisplay', 'SexCode', 'SexDisplay', 'DisplayValue', 'Numeric'],
      dtype='object')

Все значения кодов в датасете о продолжительности жизни не имеют смысла, так как коротко дублируют значения в колонках со словом Display. А также нет смысла в колонке индекс, тк он присутсвует в pandas DataFrame по умолчанию (и он не понадобится для дальнейшего соединения таблиц). А также колонки PublishState, поскольку в них одно единственное значение -- published в нашем датафрейме и на результат вычислений/анализа оно не повлияет.

In [80]:
life.drop(columns=['index', 'GhoCode', 'PublishStateCode','PublishStateDisplay',
                            'YearCode', 'RegionCode','CountryCode', 'SexCode'], inplace=True)
life

,GhoDisplay,YearDisplay,RegionDisplay,WorldBankIncomeGroupDisplay,CountryDisplay,SexDisplay,DisplayValue,Numeric
0,Life expectancy at birth (years),1990,Americas,Lower_middle_income,Nicaragua,Male,68,68.00000
1,Healthy life expectancy (HALE) at birth (years),2012,Europe,High_income,Ireland,Male,69,69.30000
2,Life expectancy at birth (years),2000,Eastern Mediterranean,Low_income,Yemen,Both sexes,61,61.00000
3,Life expectancy at birth (years),2000,Africa,Lower_middle_income,Nigeria,Female,48,48.00000
4,Life expectancy at age 60 (years),1990,South_East Asia,Lower_middle_income,Thailand,Female,19,19.00000
...,...,...,...,...,...,...,...,...
6403,Life expectancy at birth (years),2000,Eastern Mediterranean,Lower_middle_income,Morocco,Both sexes,68,68.00000
6404,Life expectancy at age 60 (years),1990,Western Pacific,Upper_middle_income,Palau,Both sexes,16,16.00000
6405,Life expectancy at birth (years),1990,Africa,Low_income,Burkina Faso,Female,51,51.00000
6406,Healthy life expectancy (HALE) at birth (years),2012,Europe,Lower_middle_income,Albania,Male,64,63.50000
6407,Life expectancy at birth (years),2013,Europe,Lower_middle_income,Armenia,Both sexes,71,71.02699

После этого для удобства переименуем названия колонок, чтобы они были короче и проще для обращения.

In [81]:
life.rename(columns = {'GhoDisplay': 'gho', 'YearDisplay' : 'year',
                       'RegionDisplay' : 'region', 'CountryDisplay' : 'country',
                       'WorldBankIncomeGroupDisplay' :'income', 'SexDisplay' : 'sex'}, inplace = True)
life.head()

,gho,year,region,income,country,sex,DisplayValue,Numeric
0,Life expectancy at birth (years),1990,Americas,Lower_middle_income,Nicaragua,Male,68,68.0
1,Healthy life expectancy (HALE) at birth (years),2012,Europe,High_income,Ireland,Male,69,69.3
2,Life expectancy at birth (years),2000,Eastern Mediterranean,Low_income,Yemen,Both sexes,61,61.0
3,Life expectancy at birth (years),2000,Africa,Lower_middle_income,Nigeria,Female,48,48.0
4,Life expectancy at age 60 (years),1990,South_East Asia,Lower_middle_income,Thailand,Female,19,19.0

В датасете с уровнем употребления алкоголя по странам лишним признаком может являться только индекс, поскольку в датафрейме он и так присутсвует автоматически. Удалим его.

In [82]:
drink.columns

Index(['index', 'country', 'beer_servings', 'spirit_servings', 'wine_servings',
       'total_litres_of_pure_alcohol'],
      dtype='object')

In [83]:
drink.drop(columns = 'index', inplace=True)
drink.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
0,Afghanistan,0,0,0,0.0
1,Albania,89,132,54,4.9
2,Algeria,25,0,14,0.7
3,Andorra,245,138,312,12.4
4,Angola,217,57,45,5.9

### 10

Посчитайте, насколько сильно коррелируют друг с другом потребления разных видов алкоголя (beer_servings,	spirit_servings и	wine_servings). Создайте датафрейм с попарными корреляциями этих столбцов друг с другом. Какие выводы можно сделать?

In [84]:
# your code here

In [85]:
drink.beer_servings.corr(drink.spirit_servings)

0.4588188741393821

In [86]:
drink.beer_servings.corr(drink.wine_servings)

0.5271716935065213

In [87]:
drink.spirit_servings.corr(drink.wine_servings)

0.1947970470098453

In [88]:
drink[['beer_servings', 'spirit_servings', 'wine_servings']].corr()

                 beer_servings  spirit_servings  wine_servings
beer_servings         1.000000         0.458819       0.527172
spirit_servings       0.458819         1.000000       0.194797
wine_servings         0.527172         0.194797       1.000000

Довольно слабо кореллирует количество выпитых крепких напитков и вина, что довольно логично, но сильнее между собой кореллирует пиво и вино, средне крепкий напиток и пиво, однако все эти взаимосвязи не близки к 1, так что можно сказать, что сильной взаимосвязи нельзя выявить.

### 11

Каким образом следует осуществить соединение двух имеющихся у нас таблиц? Почему? Соедините таблицы!

Получилось ли у вас задействовать все строки, и если нет, то почему? Что делать с теми строками, которые не удается задействовать, если таковые есть? Ответ обоснуйте.

*Подсказка. В ответе на первый вопрос задания, а также в обосновании способа соединения таблиц вам может помочь задание 3 данного раздела ДЗ и соответствующий семинарский ноутбук!*

*Примечание. Не забудьте сохранить все изменения! В последующих заданиях вы должны работать с одним объединенным датасетом.*

Для начала преобразуем значения стран в более подходящий вид, чтобы они совпадали у датасетов.

In [89]:
drink.country.unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua & Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia-Herzegovina', 'Botswana', 'Brazil', 'Brunei',
       'Bulgaria', 'Burkina Faso', 'Burundi', "Cote d'Ivoire",
       'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Comoros', 'Congo', 'Cook Islands', 'Costa Rica', 'Croatia',
       'Cuba', 'Cyprus', 'Czech Republic', 'North Korea', 'DR Congo',
       'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador',
       'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia',
       'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras',
       'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq',
       'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan', 'Laos',
       'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Lithuania',
       'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives',
       'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius',
       'Mexico', 'Micronesia', 'Monaco', 'Mongolia', 'Montenegro',
       'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal',
       'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
       'Niue', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Qatar', 'South Korea', 'Moldova', 'Romania',
       'Russian Federation', 'Rwanda', 'St. Kitts & Nevis', 'St. Lucia',
       'St. Vincent & the Grenadines', 'Samoa', 'San Marino',
       'Sao Tome & Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'Spain', 'Sri Lanka',
       'Sudan', 'Suriname', 'Swaziland', 'Sweden', 'Switzerland', 'Syria',
       'Tajikistan', 'Thailand', 'Macedonia', 'Timor-Leste', 'Togo',
       'Tonga', 'Trinidad & Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'Tanzania', 'USA', 'Uruguay', 'Uzbekistan',
       'Vanuatu', 'Venezuela', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe'],
      dtype=object)

In [90]:
cl = set(life.sort_values('country').country.unique())

In [91]:
#заменим все амперсанты на слово and с помощью работы со строками
drink['country'] = drink.country.str.replace('&', 'and')
cd = set(drink.country.unique())

In [92]:
cl.difference(cd)

{'Bolivia (Plurinational State of)',
 'Bosnia and Herzegovina',
 'Brunei Darussalam',
 "Côte d'Ivoire",
 "Democratic People's Republic of Korea",
 'Democratic Republic of the Congo',
 'Guinea_Bissau',
 'Iran (Islamic Republic of)',
 "Lao People's Democratic Republic",
 'Micronesia (Federated States of)',
 'Republic of Korea',
 'Republic of Moldova',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'South Sudan',
 'Syrian Arab Republic',
 'The former Yugoslav republic of Macedonia',
 'Timor_Leste',
 'United Kingdom of Great Britain and Northern Ireland',
 'United Republic of Tanzania',
 'United States of America',
 'Venezuela (Bolivarian Republic of)',
 'Viet Nam'}

In [93]:
cd.difference(cl)

{'Bolivia',
 'Bosnia-Herzegovina',
 'Brunei',
 "Cote d'Ivoire",
 'DR Congo',
 'Guinea-Bissau',
 'Iran',
 'Laos',
 'Macedonia',
 'Micronesia',
 'Moldova',
 'North Korea',
 'South Korea',
 'St. Kitts and Nevis',
 'St. Lucia',
 'St. Vincent and the Grenadines',
 'Syria',
 'Tanzania',
 'Timor-Leste',
 'USA',
 'United Kingdom',
 'Venezuela',
 'Vietnam'}

In [94]:
life = life.replace({'country' : {'Bolivia (Plurinational State of)' : 'Bolivia', 'Bosnia and Herzegovina' : 'Bosnia-Herzegovina',
                                  'Brunei Darussalam' : 'Brunei', "Côte d'Ivoire" : "Cote d'Ivoire", "Democratic People's Republic of Korea" : 'North Korea',
                                  'Democratic Republic of the Congo' : 'DR Congo', 'Guinea_Bissau' : 'Guinea-Bissau', 'Iran (Islamic Republic of)' : 'Iran',
                                  "Lao People's Democratic Republic" : 'Laos', 'Micronesia (Federated States of)' : 'Micronesia', 'Republic of Korea' : 'South Korea',
                                  'Republic of Moldova' : 'Moldova', 'Saint Kitts and Nevis' :'St. Kitts and Nevis', 'Saint Lucia' : 'St. Lucia',
                                  'Saint Vincent and the Grenadines' : 'St. Vincent and the Grenadines', 'Syrian Arab Republic' : 'Syria',
                                  'The former Yugoslav republic of Macedonia' : 'Macedonia', 'Timor_Leste' : 'Timor-Leste',
                                  'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom', 'United Republic of Tanzania' : 'Tanzania',
                                  'United States of America' : 'USA', 'Venezuela (Bolivarian Republic of)' : 'Venezuela', 'Viet Nam' : 'Vietnam'}})

In [95]:
cl = set(life.sort_values('country').country.unique())
cl.difference(cd)

{'South Sudan'}

In [96]:
data = pd.merge(life, drink, how='inner', left_on = 'country', right_on ='country')

In [97]:
data.shape

(6369, 12)

In [98]:
data

,gho,year,region,income,country,sex,DisplayValue,Numeric,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
0,Life expectancy at birth (years),1990,Americas,Lower_middle_income,Nicaragua,Male,68,68.00000,78,118,1,3.5
1,Healthy life expectancy (HALE) at birth (years),2013,Americas,Lower_middle_income,Nicaragua,Male,62,61.90000,78,118,1,3.5
2,Life expectancy at birth (years),1990,Americas,Lower_middle_income,Nicaragua,Female,74,74.00000,78,118,1,3.5
3,Life expectancy at birth (years),2000,Americas,Lower_middle_income,Nicaragua,Female,76,76.00000,78,118,1,3.5
4,Life expectancy at birth (years),2000,Americas,Lower_middle_income,Nicaragua,Male,70,70.00000,78,118,1,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...
6364,Healthy life expectancy (HALE) at birth (years),2013,Europe,High_income,Belgium,Female,72,72.40000,295,84,212,10.5
6365,Life expectancy at age 60 (years),2000,Europe,High_income,Belgium,Both sexes,22,22.00000,295,84,212,10.5
6366,Life expectancy at birth (years),2000,Europe,High_income,Belgium,Male,75,75.00000,295,84,212,10.5
6367,Life expectancy at birth (years),2012,Europe,High_income,Belgium,Male,78,78.00000,295,84,212,10.5
6368,Life expectancy at birth (years),2013,Europe,High_income,Belgium,Both sexes,80,80.48828,295,84,212,10.5

Сделали соединение по стране, поскольку это единственное общее у двух датасетов, а также хочется отметить, что сложно назвать статистику второго датасета по напиткам репрезентативной, поскольку она касается людей всех возрастов, а также не учитывает пол и другое.

### 12

Осуществите группировку данных по странам и типу научной статьи (многомерная группировка). В качестве столбцов значений для группировки возьмите оцененную продолжительность жизни и общее потребление алкоголя в литрах. В качестве агреггирующих функций для продолжительности жизни возьмите среднее, медиану, минимум и максимум, а для потребления алкоголя — агреггирующую функцию/функции выберите самостоятельно. Как вы можете прокомментировать свой выбор и что вы наблюдаете?

In [99]:
data.groupby(['country', 'gho'])[['DisplayValue', 'Numeric', 'total_litres_of_pure_alcohol']].agg({
    'Numeric' : ['mean', 'median', 'min', 'max'], 'DisplayValue' : ['mean', 'median', 'min', 'max'],
    'total_litres_of_pure_alcohol' : ['mean', 'sum']})

                                                               Numeric  \
                                                                  mean
country     gho
Afghanistan Healthy life expectancy (HALE) at birth (years)  47.833333
            Life expectancy at age 60 (years)                15.223012
            Life expectancy at birth (years)                 56.311805
Albania     Healthy life expectancy (HALE) at birth (years)  63.800000
            Life expectancy at age 60 (years)                17.728610
...                                                                ...
Zambia      Life expectancy at age 60 (years)                16.068835
            Life expectancy at birth (years)                 49.953199
Zimbabwe    Healthy life expectancy (HALE) at birth (years)  45.222222
            Life expectancy at age 60 (years)                17.369381
            Life expectancy at birth (years)                 55.186778

                                                                              \
                                                                median   min
country     gho
Afghanistan Healthy life expectancy (HALE) at birth (years)  48.800000  44.6
            Life expectancy at age 60 (years)                15.061535  13.0
            Life expectancy at birth (years)                 57.000000  49.0
Albania     Healthy life expectancy (HALE) at birth (years)  63.900000  59.9
            Life expectancy at age 60 (years)                18.000000  15.0
...                                                                ...   ...
Zambia      Life expectancy at age 60 (years)                16.000000  14.0
            Life expectancy at birth (years)                 51.000000  40.0
Zimbabwe    Healthy life expectancy (HALE) at birth (years)  47.700000  36.4
            Life expectancy at age 60 (years)                17.654040  15.0
            Life expectancy at birth (years)                 58.363385  42.0

                                                                       \
                                                                  max
country     gho
Afghanistan Healthy life expectancy (HALE) at birth (years)  50.50000
            Life expectancy at age 60 (years)                17.00000
            Life expectancy at birth (years)                 61.97733
Albania     Healthy life expectancy (HALE) at birth (years)  66.00000
            Life expectancy at age 60 (years)                20.00000
...                                                               ...
Zambia      Life expectancy at age 60 (years)                18.10310
            Life expectancy at birth (years)                 60.01617
Zimbabwe    Healthy life expectancy (HALE) at birth (years)  51.80000
            Life expectancy at age 60 (years)                19.00000
            Life expectancy at birth (years)                 64.00000

                                                            DisplayValue  \
                                                                    mean
country     gho
Afghanistan Healthy life expectancy (HALE) at birth (years)    48.000000
            Life expectancy at age 60 (years)                  15.250000
            Life expectancy at birth (years)                   56.333333
Albania     Healthy life expectancy (HALE) at birth (years)    64.000000
            Life expectancy at age 60 (years)                  17.750000
...                                                                  ...
Zambia      Life expectancy at age 60 (years)                  16.000000
            Life expectancy at birth (years)                   49.916667
Zimbabwe    Healthy life expectancy (HALE) at birth (years)    45.222222
            Life expectancy at age 60 (years)                  17.333333
            Life expectancy at birth (years)                   55.166667

                                                                            \
                                                            median min max
country     gho
Afghanistan Healthy life expectancy (HALE) at birth (years)   49.0  45  50
            Life expectancy at age 60 (years)                 15.0  13  17
            Life expectancy at birth (years)                  57.0  49  62
Albania     Healthy life expectancy (HALE) at birth (years)   64.0  60  66
            Life expectancy at age 60 (years)                 18.0  15  20
...                                                            ...  ..  ..
Zambia      Life expectancy at age 60 (years)                 16.0  14  18
            Life expectancy at birth (years)                  51.0  40  60
Zimbabwe    Healthy life expectancy (HALE) at birth (years)   48.0  36  52
            Life expectancy at age 60 (years)                 17.5  15  19
            Life expectancy at birth (years)                  58.5  42  64

                                                            total_litres_of_pure_alcohol  \
                                                                                    mean
country     gho
Afghanistan Healthy life expectancy (HALE) at birth (years)                          0.0
            Life expectancy at age 60 (years)                                        0.0
            Life expectancy at birth (years)                                         0.0
Albania     Healthy life expectancy (HALE) at birth (years)                          4.9
            Life expectancy at age 60 (years)                                        4.9
...                                                                                  ...
Zambia      Life expectancy at age 60 (years)                                        2.5
            Life expectancy at birth (years)                                         2.5
Zimbabwe    Healthy life expectancy (HALE) at birth (years)                          4.7
            Life expectancy at age 60 (years)                                        4.7
            Life expectancy at birth (years)                                         4.7


                                                              sum
country     gho
Afghanistan Healthy life expectancy (HALE) at birth (years)   0.0
            Life expectancy at age 60 (years)                 0.0
            Life expectancy at birth (years)                  0.0
Albania     Healthy life expectancy (HALE) at birth (years)  44.1
            Life expectancy at age 60 (years)                58.8
...                                                           ...
Zambia      Life expectancy at age 60 (years)                30.0
            Life expectancy at birth (years)                 30.0
Zimbabwe    Healthy life expectancy (HALE) at birth (years)  42.3
            Life expectancy at age 60 (years)                56.4
            Life expectancy at birth (years)                 56.4

[579 rows x 10 columns]

In [100]:
gr = data.groupby(['country', 'gho'])[['DisplayValue', 'Numeric', 'total_litres_of_pure_alcohol']].agg({
    'Numeric' : ['mean', 'median', 'min', 'max'], 'DisplayValue' : ['mean', 'median', 'min', 'max'],
    'total_litres_of_pure_alcohol' : ['mean', 'sum']})

В общем количестве алкоголя наиболее логичным будет взять среднее значение, но оно вообще никак не меняется, поскольку значения взяты исключительно по стране, поэтому можно взять кумулятивное значение.

### 13

Вставьте любые два столбца из предыдущего задания, которые вы получили путем группировки, в исходную таблицу в качестве двух новых столбцов (назвать вы их можете как хотите). Разумеется, значения этих столбцов должны соответствовать значениям исходной таблицы по указанным в прошлом задании категориям.

*Примечание. Не забудьте сохранить все изменения! В последующих заданиях вы должны работать с обновленным датасетом.*

In [101]:
gr1 = data.groupby(['country', 'gho']).agg({'Numeric': ['mean', 'min'],}).reset_index()
gr1.columns = ['country', 'gho', 'avg_life_expectancy', 'min_life_expectancy']

data1 = pd.merge(data, gr1, on=['country', 'gho'], how='left')

data1

,gho,year,region,income,country,sex,DisplayValue,Numeric,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,avg_life_expectancy,min_life_expectancy
0,Life expectancy at birth (years),1990,Americas,Lower_middle_income,Nicaragua,Male,68,68.00000,78,118,1,3.5,72.667402,68.0
1,Healthy life expectancy (HALE) at birth (years),2013,Americas,Lower_middle_income,Nicaragua,Male,62,61.90000,78,118,1,3.5,63.522222,60.9
2,Life expectancy at birth (years),1990,Americas,Lower_middle_income,Nicaragua,Female,74,74.00000,78,118,1,3.5,72.667402,68.0
3,Life expectancy at birth (years),2000,Americas,Lower_middle_income,Nicaragua,Female,76,76.00000,78,118,1,3.5,72.667402,68.0
4,Life expectancy at birth (years),2000,Americas,Lower_middle_income,Nicaragua,Male,70,70.00000,78,118,1,3.5,72.667402,68.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6364,Healthy life expectancy (HALE) at birth (years),2013,Europe,High_income,Belgium,Female,72,72.40000,295,84,212,10.5,69.822222,66.1
6365,Life expectancy at age 60 (years),2000,Europe,High_income,Belgium,Both sexes,22,22.00000,295,84,212,10.5,22.216374,18.0
6366,Life expectancy at birth (years),2000,Europe,High_income,Belgium,Male,75,75.00000,295,84,212,10.5,78.700214,73.0
6367,Life expectancy at birth (years),2012,Europe,High_income,Belgium,Male,78,78.00000,295,84,212,10.5,78.700214,73.0
6368,Life expectancy at birth (years),2013,Europe,High_income,Belgium,Both sexes,80,80.48828,295,84,212,10.5,78.700214,73.0

Добавила значения со средним и с минимальным по продолжительности жизни, поскольку будет удобнее сранивать и добавлять признаки с отклонением, чтобы не группировать еще раз данные.

### 14

Используя группировки, аргументированно ответьте на вопрос: на каких континентах средняя ожидаемая продолжительность жизни выше у мужчин, а на каких у женщин?

А медианная ожидаемая продолжительность?

А минимальная ожидаемая продолжительность?

Сделайте выводы!

*Подсказка. Казалось бы, при чем здесь тип научной статьи?*

In [102]:
grouped_life = data1.groupby(['region', 'sex', 'gho']).Numeric.agg(['mean', 'median', 'min'])
grouped_life

                                                                                       mean  \
region                sex        gho
Africa                Both sexes Healthy life expectancy (HALE) at birth (years)  49.136232
                                 Life expectancy at age 60 (years)                16.108968
                                 Life expectancy at birth (years)                 56.244803
                      Female     Healthy life expectancy (HALE) at birth (years)  50.094203
                                 Life expectancy at age 60 (years)                16.792173
                                 Life expectancy at birth (years)                 57.847483
                      Male       Healthy life expectancy (HALE) at birth (years)  48.190580
                                 Life expectancy at age 60 (years)                15.329190
                                 Life expectancy at birth (years)                 54.720970
Americas              Both sexes Healthy life expectancy (HALE) at birth (years)  63.838095
                                 Life expectancy at age 60 (years)                20.690960
                                 Life expectancy at birth (years)                 73.028041
                      Female     Healthy life expectancy (HALE) at birth (years)  65.971429
                                 Life expectancy at age 60 (years)                22.131179
                                 Life expectancy at birth (years)                 75.873706
                      Male       Healthy life expectancy (HALE) at birth (years)  61.752381
                                 Life expectancy at age 60 (years)                19.175239
                                 Life expectancy at birth (years)                 70.282002
Eastern Mediterranean Both sexes Healthy life expectancy (HALE) at birth (years)  60.279365
                                 Life expectancy at age 60 (years)                18.040616
                                 Life expectancy at birth (years)                 68.828298
                      Female     Healthy life expectancy (HALE) at birth (years)  60.960317
                                 Life expectancy at age 60 (years)                18.959319
                                 Life expectancy at birth (years)                 70.590926
                      Male       Healthy life expectancy (HALE) at birth (years)  59.601587
                                 Life expectancy at age 60 (years)                17.289760
                                 Life expectancy at birth (years)                 67.283447
Europe                Both sexes Healthy life expectancy (HALE) at birth (years)  66.658491
                                 Life expectancy at age 60 (years)                20.566757
                                 Life expectancy at birth (years)                 75.233666
                      Female     Healthy life expectancy (HALE) at birth (years)  69.118868
                                 Life expectancy at age 60 (years)                22.292036
                                 Life expectancy at birth (years)                 78.454599
                      Male       Healthy life expectancy (HALE) at birth (years)  64.174214
                                 Life expectancy at age 60 (years)                18.476702
                                 Life expectancy at birth (years)                 71.976935
South_East Asia       Both sexes Healthy life expectancy (HALE) at birth (years)  59.403030
                                 Life expectancy at age 60 (years)                17.360583
                                 Life expectancy at birth (years)                 66.345093
                      Female     Healthy life expectancy (HALE) at birth (years)  60.909091
                                 Life expectancy at age 60 (years)                18.342758
                                 Life expectancy at birth (years)                 68.188877
                      Male       Healthy life expectancy (HALE) at birth (years)  57.942424
                                 Life expectancy at age 60 (years)                16.291729
                                 Life expectancy at birth (years)                 64.491738
Western Pacific       Both sexes Healthy life expectancy (HALE) at birth (years)  62.924691
                                 Life expectancy at age 60 (years)                18.785198
                                 Life expectancy at birth (years)                 70.985250
                      Female     Healthy life expectancy (HALE) at birth (years)  64.733333
                                 Life expectancy at age 60 (years)                20.359732
                                 Life expectancy at birth (years)                 73.538356
                      Male       Healthy life expectancy (HALE) at birth (years)  61.219753
                                 Life expectancy at age 60 (years)                17.236480
                                 Life expectancy at birth (years)                 68.585153

                                                                                     median  \
region                sex        gho
Africa                Both sexes Healthy life expectancy (HALE) at birth (years)  49.350000
                                 Life expectancy at age 60 (years)                16.000000
                                 Life expectancy at birth (years)                 57.000000
                      Female     Healthy life expectancy (HALE) at birth (years)  50.000000
                                 Life expectancy at age 60 (years)                16.943585
                                 Life expectancy at birth (years)                 58.000000
                      Male       Healthy life expectancy (HALE) at birth (years)  48.800000
                                 Life expectancy at age 60 (years)                15.099685
                                 Life expectancy at birth (years)                 55.000000
Americas              Both sexes Healthy life expectancy (HALE) at birth (years)  63.800000
                                 Life expectancy at age 60 (years)                21.000000
                                 Life expectancy at birth (years)                 74.000000
                      Female     Healthy life expectancy (HALE) at birth (years)  66.200000
                                 Life expectancy at age 60 (years)                22.538210
                                 Life expectancy at birth (years)                 77.000000
                      Male       Healthy life expectancy (HALE) at birth (years)  62.100000
                                 Life expectancy at age 60 (years)                19.343050
                                 Life expectancy at birth (years)                 71.000000
Eastern Mediterranean Both sexes Healthy life expectancy (HALE) at birth (years)  62.300000
                                 Life expectancy at age 60 (years)                18.000000
                                 Life expectancy at birth (years)                 70.989760
                      Female     Healthy life expectancy (HALE) at birth (years)  63.500000
                                 Life expectancy at age 60 (years)                19.000000
                                 Life expectancy at birth (years)                 73.000000
                      Male       Healthy life expectancy (HALE) at birth (years)  61.700000
                                 Life expectancy at age 60 (years)                17.000000
                                 Life expectancy at birth (years)                 69.000000
Europe                Both sexes Healthy life expectancy (HALE) at birth (years)  67.400000
                                 Life expectancy at age 60 (years)                20.118920
                                 Life expectancy at birth (years)                 76.000000
                      Female     Healthy life expectancy (HALE) at birth (years)  70.000000
                                 Life expectancy at age 60 (years)                22.000000
                                 Life expectancy at birth (years)                 79.000000
                      Male       Healthy life expectancy (HALE) at birth (years)  64.800000
                                 Life expectancy at age 60 (years)                18.000000
                                 Life expectancy at birth (years)                 72.518745
South_East Asia       Both sexes Healthy life expectancy (HALE) at birth (years)  58.900000
                                 Life expectancy at age 60 (years)                17.000000
                                 Life expectancy at birth (years)                 67.500000
                      Female     Healthy life expectancy (HALE) at birth (years)  59.900000
                                 Life expectancy at age 60 (years)                18.000000
                                 Life expectancy at birth (years)                 68.968250
                      Male       Healthy life expectancy (HALE) at birth (years)  58.200000
                                 Life expectancy at age 60 (years)                16.000000
                                 Life expectancy at birth (years)                 65.000000
Western Pacific       Both sexes Healthy life expectancy (HALE) at birth (years)  62.200000
                                 Life expectancy at age 60 (years)                18.000000
                                 Life expectancy at birth (years)                 71.000000
                      Female     Healthy life expectancy (HALE) at birth (years)  63.700000
                                 Life expectancy at age 60 (years)                19.000000
                                 Life expectancy at birth (years)                 73.500000
                      Male       Healthy life expectancy (HALE) at birth (years)  60.800000
                                 Life expectancy at age 60 (years)                16.658970
                                 Life expectancy at birth (years)                 68.124050

                                                                                       min
region                sex        gho
Africa                Both sexes Healthy life expectancy (HALE) at birth (years)  33.10000
                                 Life expectancy at age 60 (years)                11.00000
                                 Life expectancy at birth (years)                 38.00000
                      Female     Healthy life expectancy (HALE) at birth (years)  33.40000
                                 Life expectancy at age 60 (years)                11.00000
                                 Life expectancy at birth (years)                 38.00000
                      Male       Healthy life expectancy (HALE) at birth (years)  32.80000
                                 Life expectancy at age 60 (years)                11.00000
                                 Life expectancy at birth (years)                 38.00000
Americas              Both sexes Healthy life expectancy (HALE) at birth (years)  47.80000
                                 Life expectancy at age 60 (years)                15.00000
                                 Life expectancy at birth (years)                 54.00000
                      Female     Healthy life expectancy (HALE) at birth (years)  48.50000
                                 Life expectancy at age 60 (years)                16.00000
                                 Life expectancy at birth (years)                 56.00000
                      Male       Healthy life expectancy (HALE) at birth (years)  47.10000
                                 Life expectancy at age 60 (years)                12.86658
                                 Life expectancy at birth (years)                 52.00000
Eastern Mediterranean Both sexes Healthy life expectancy (HALE) at birth (years)  42.90000
                                 Life expectancy at age 60 (years)                14.00000
                                 Life expectancy at birth (years)                 47.00000
                      Female     Healthy life expectancy (HALE) at birth (years)  43.70000
                                 Life expectancy at age 60 (years)                15.00000
                                 Life expectancy at birth (years)                 50.00000
                      Male       Healthy life expectancy (HALE) at birth (years)  42.00000
                                 Life expectancy at age 60 (years)                13.00000
                                 Life expectancy at birth (years)                 45.00000
Europe                Both sexes Healthy life expectancy (HALE) at birth (years)  54.30000
                                 Life expectancy at age 60 (years)                15.00000
                                 Life expectancy at birth (years)                 62.00000
                      Female     Healthy life expectancy (HALE) at birth (years)  56.60000
                                 Life expectancy at age 60 (years)                16.00000
                                 Life expectancy at birth (years)                 65.00000
                      Male       Healthy life expectancy (HALE) at birth (years)  51.20000
                                 Life expectancy at age 60 (years)                12.00000
                                 Life expectancy at birth (years)                 58.00000
South_East Asia       Both sexes Healthy life expectancy (HALE) at birth (years)  50.00000
                                 Life expectancy at age 60 (years)                13.00000
                                 Life expectancy at birth (years)                 50.00000
                      Female     Healthy life expectancy (HALE) at birth (years)  51.20000
                                 Life expectancy at age 60 (years)                12.00000
                                 Life expectancy at birth (years)                 51.00000
                      Male       Healthy life expectancy (HALE) at birth (years)  48.80000
                                 Life expectancy at age 60 (years)                12.00000
                                 Life expectancy at birth (years)                 48.00000
Western Pacific       Both sexes Healthy life expectancy (HALE) at birth (years)  50.20000
                                 Life expectancy at age 60 (years)                13.00000
                                 Life expectancy at birth (years)                 53.00000
                      Female     Healthy life expectancy (HALE) at birth (years)  51.80000
                                 Life expectancy at age 60 (years)                15.00000
                                 Life expectancy at birth (years)                 54.00000
                      Male       Healthy life expectancy (HALE) at birth (years)  48.60000
                                 Life expectancy at age 60 (years)                12.00000
                                 Life expectancy at birth (years)                 51.00000

In [160]:
grouped_life['mean'].unstack(level=1)[grouped_life['mean'].unstack(level=1)['Female'] >
                                      grouped_life['mean'].unstack(level=1)['Male']]

sex                                                                    Both sexes  \
region                gho
Africa                Healthy life expectancy (HALE) at birth (years)   49.136232
                      Life expectancy at age 60 (years)                 16.108968
                      Life expectancy at birth (years)                  56.244803
Americas              Healthy life expectancy (HALE) at birth (years)   63.838095
                      Life expectancy at age 60 (years)                 20.690960
                      Life expectancy at birth (years)                  73.028041
Eastern Mediterranean Healthy life expectancy (HALE) at birth (years)   60.279365
                      Life expectancy at age 60 (years)                 18.040616
                      Life expectancy at birth (years)                  68.828298
Europe                Healthy life expectancy (HALE) at birth (years)   66.658491
                      Life expectancy at age 60 (years)                 20.566757
                      Life expectancy at birth (years)                  75.233666
South_East Asia       Healthy life expectancy (HALE) at birth (years)   59.403030
                      Life expectancy at age 60 (years)                 17.360583
                      Life expectancy at birth (years)                  66.345093
Western Pacific       Healthy life expectancy (HALE) at birth (years)   62.924691
                      Life expectancy at age 60 (years)                 18.785198
                      Life expectancy at birth (years)                  70.985250

sex                                                                       Female  \
region                gho
Africa                Healthy life expectancy (HALE) at birth (years)  50.094203
                      Life expectancy at age 60 (years)                16.792173
                      Life expectancy at birth (years)                 57.847483
Americas              Healthy life expectancy (HALE) at birth (years)  65.971429
                      Life expectancy at age 60 (years)                22.131179
                      Life expectancy at birth (years)                 75.873706
Eastern Mediterranean Healthy life expectancy (HALE) at birth (years)  60.960317
                      Life expectancy at age 60 (years)                18.959319
                      Life expectancy at birth (years)                 70.590926
Europe                Healthy life expectancy (HALE) at birth (years)  69.118868
                      Life expectancy at age 60 (years)                22.292036
                      Life expectancy at birth (years)                 78.454599
South_East Asia       Healthy life expectancy (HALE) at birth (years)  60.909091
                      Life expectancy at age 60 (years)                18.342758
                      Life expectancy at birth (years)                 68.188877
Western Pacific       Healthy life expectancy (HALE) at birth (years)  64.733333
                      Life expectancy at age 60 (years)                20.359732
                      Life expectancy at birth (years)                 73.538356

sex                                                                         Male
region                gho
Africa                Healthy life expectancy (HALE) at birth (years)  48.190580
                      Life expectancy at age 60 (years)                15.329190
                      Life expectancy at birth (years)                 54.720970
Americas              Healthy life expectancy (HALE) at birth (years)  61.752381
                      Life expectancy at age 60 (years)                19.175239
                      Life expectancy at birth (years)                 70.282002
Eastern Mediterranean Healthy life expectancy (HALE) at birth (years)  59.601587
                      Life expectancy at age 60 (years)                17.289760
                      Life expectancy at birth (years)                 67.283447
Europe                Healthy life expectancy (HALE) at birth (years)  64.174214
                      Life expectancy at age 60 (years)                18.476702
                      Life expectancy at birth (years)                 71.976935
South_East Asia       Healthy life expectancy (HALE) at birth (years)  57.942424
                      Life expectancy at age 60 (years)                16.291729
                      Life expectancy at birth (years)                 64.491738
Western Pacific       Healthy life expectancy (HALE) at birth (years)  61.219753
                      Life expectancy at age 60 (years)                17.236480
                      Life expectancy at birth (years)                 68.585153

In [157]:
grouped_life['mean'].unstack(level=1)[grouped_life['mean'].unstack(level=1)['Female'] <
                                      grouped_life['mean'].unstack(level=1)['Male']]

Empty DataFrame
Columns: [Both sexes, Female, Male]
Index: []

In [161]:
grouped_life['median'].unstack(level=1)[grouped_life['median'].unstack(level=1)['Female'] >
                                      grouped_life['median'].unstack(level=1)['Male']]

sex                                                                    Both sexes  \
region                gho
Africa                Healthy life expectancy (HALE) at birth (years)    49.35000
                      Life expectancy at age 60 (years)                  16.00000
                      Life expectancy at birth (years)                   57.00000
Americas              Healthy life expectancy (HALE) at birth (years)    63.80000
                      Life expectancy at age 60 (years)                  21.00000
                      Life expectancy at birth (years)                   74.00000
Eastern Mediterranean Healthy life expectancy (HALE) at birth (years)    62.30000
                      Life expectancy at age 60 (years)                  18.00000
                      Life expectancy at birth (years)                   70.98976
Europe                Healthy life expectancy (HALE) at birth (years)    67.40000
                      Life expectancy at age 60 (years)                  20.11892
                      Life expectancy at birth (years)                   76.00000
South_East Asia       Healthy life expectancy (HALE) at birth (years)    58.90000
                      Life expectancy at age 60 (years)                  17.00000
                      Life expectancy at birth (years)                   67.50000
Western Pacific       Healthy life expectancy (HALE) at birth (years)    62.20000
                      Life expectancy at age 60 (years)                  18.00000
                      Life expectancy at birth (years)                   71.00000

sex                                                                       Female  \
region                gho
Africa                Healthy life expectancy (HALE) at birth (years)  50.000000
                      Life expectancy at age 60 (years)                16.943585
                      Life expectancy at birth (years)                 58.000000
Americas              Healthy life expectancy (HALE) at birth (years)  66.200000
                      Life expectancy at age 60 (years)                22.538210
                      Life expectancy at birth (years)                 77.000000
Eastern Mediterranean Healthy life expectancy (HALE) at birth (years)  63.500000
                      Life expectancy at age 60 (years)                19.000000
                      Life expectancy at birth (years)                 73.000000
Europe                Healthy life expectancy (HALE) at birth (years)  70.000000
                      Life expectancy at age 60 (years)                22.000000
                      Life expectancy at birth (years)                 79.000000
South_East Asia       Healthy life expectancy (HALE) at birth (years)  59.900000
                      Life expectancy at age 60 (years)                18.000000
                      Life expectancy at birth (years)                 68.968250
Western Pacific       Healthy life expectancy (HALE) at birth (years)  63.700000
                      Life expectancy at age 60 (years)                19.000000
                      Life expectancy at birth (years)                 73.500000

sex                                                                         Male
region                gho
Africa                Healthy life expectancy (HALE) at birth (years)  48.800000
                      Life expectancy at age 60 (years)                15.099685
                      Life expectancy at birth (years)                 55.000000
Americas              Healthy life expectancy (HALE) at birth (years)  62.100000
                      Life expectancy at age 60 (years)                19.343050
                      Life expectancy at birth (years)                 71.000000
Eastern Mediterranean Healthy life expectancy (HALE) at birth (years)  61.700000
                      Life expectancy at age 60 (years)                17.000000
                      Life expectancy at birth (years)                 69.000000
Europe                Healthy life expectancy (HALE) at birth (years)  64.800000
                      Life expectancy at age 60 (years)                18.000000
                      Life expectancy at birth (years)                 72.518745
South_East Asia       Healthy life expectancy (HALE) at birth (years)  58.200000
                      Life expectancy at age 60 (years)                16.000000
                      Life expectancy at birth (years)                 65.000000
Western Pacific       Healthy life expectancy (HALE) at birth (years)  60.800000
                      Life expectancy at age 60 (years)                16.658970
                      Life expectancy at birth (years)                 68.124050

In [162]:
grouped_life['median'].unstack(level=1)[grouped_life['median'].unstack(level=1)['Female'] <
                                      grouped_life['median'].unstack(level=1)['Male']]

Empty DataFrame
Columns: [Both sexes, Female, Male]
Index: []

In [163]:
grouped_life['min'].unstack(level=1)[grouped_life['min'].unstack(level=1)['Female'] >
                                      grouped_life['min'].unstack(level=1)['Male']]

sex                                                                    Both sexes  \
region                gho
Africa                Healthy life expectancy (HALE) at birth (years)        33.1
Americas              Healthy life expectancy (HALE) at birth (years)        47.8
                      Life expectancy at age 60 (years)                      15.0
                      Life expectancy at birth (years)                       54.0
Eastern Mediterranean Healthy life expectancy (HALE) at birth (years)        42.9
                      Life expectancy at age 60 (years)                      14.0
                      Life expectancy at birth (years)                       47.0
Europe                Healthy life expectancy (HALE) at birth (years)        54.3
                      Life expectancy at age 60 (years)                      15.0
                      Life expectancy at birth (years)                       62.0
South_East Asia       Healthy life expectancy (HALE) at birth (years)        50.0
                      Life expectancy at birth (years)                       50.0
Western Pacific       Healthy life expectancy (HALE) at birth (years)        50.2
                      Life expectancy at age 60 (years)                      13.0
                      Life expectancy at birth (years)                       53.0

sex                                                                    Female  \
region                gho
Africa                Healthy life expectancy (HALE) at birth (years)    33.4
Americas              Healthy life expectancy (HALE) at birth (years)    48.5
                      Life expectancy at age 60 (years)                  16.0
                      Life expectancy at birth (years)                   56.0
Eastern Mediterranean Healthy life expectancy (HALE) at birth (years)    43.7
                      Life expectancy at age 60 (years)                  15.0
                      Life expectancy at birth (years)                   50.0
Europe                Healthy life expectancy (HALE) at birth (years)    56.6
                      Life expectancy at age 60 (years)                  16.0
                      Life expectancy at birth (years)                   65.0
South_East Asia       Healthy life expectancy (HALE) at birth (years)    51.2
                      Life expectancy at birth (years)                   51.0
Western Pacific       Healthy life expectancy (HALE) at birth (years)    51.8
                      Life expectancy at age 60 (years)                  15.0
                      Life expectancy at birth (years)                   54.0

sex                                                                        Male
region                gho
Africa                Healthy life expectancy (HALE) at birth (years)  32.80000
Americas              Healthy life expectancy (HALE) at birth (years)  47.10000
                      Life expectancy at age 60 (years)                12.86658
                      Life expectancy at birth (years)                 52.00000
Eastern Mediterranean Healthy life expectancy (HALE) at birth (years)  42.00000
                      Life expectancy at age 60 (years)                13.00000
                      Life expectancy at birth (years)                 45.00000
Europe                Healthy life expectancy (HALE) at birth (years)  51.20000
                      Life expectancy at age 60 (years)                12.00000
                      Life expectancy at birth (years)                 58.00000
South_East Asia       Healthy life expectancy (HALE) at birth (years)  48.80000
                      Life expectancy at birth (years)                 48.00000
Western Pacific       Healthy life expectancy (HALE) at birth (years)  48.60000
                      Life expectancy at age 60 (years)                12.00000
                      Life expectancy at birth (years)                 51.00000

In [164]:
grouped_life['min'].unstack(level=1)[grouped_life['min'].unstack(level=1)['Female'] <
                                      grouped_life['min'].unstack(level=1)['Male']]

Empty DataFrame
Columns: [Both sexes, Female, Male]
Index: []

Средняя, медианная и минмальная продолжительность жизни выше у женщин на всех континентах независимо от статьи.

### 15

Работая лишь с общим объединенным датасетом и не используя исходную таблицу drinks, подсчитайте среднее потребление каждого вида алкоголя и среднее общее количество литров потребляемого алкоголя на человека по всем континентам. Занесите ваши результаты в отдельный датафрейм!

*Подсказка. Задача немного сложнее, чем может показаться на первый взгляд — в объединенном датасете страны встречаются разное количество раз, и из-за этого могут возникнуть определенные проблемы. Если так случится, надо подумать, как это обойти!*

*Примечание. Разумеется, это необходимо сделать автоматизированно, а не перебирая каждый континент по отдельности.*

In [103]:
data1.groupby('region')[['beer_servings', 'wine_servings', 'spirit_servings', 'total_litres_of_pure_alcohol']].mean()

,beer_servings,wine_servings,spirit_servings,total_litres_of_pure_alcohol
region,,,,
Africa,68.826087,18.000000,17.304348,3.360870
Americas,155.600000,37.514286,148.257143,6.102857
Eastern Mediterranean,10.428571,4.857143,21.190476,0.714286
Europe,175.132075,123.528302,130.415094,7.873585
South_East Asia,14.818182,0.454545,44.090909,1.063636
Western Pacific,81.962963,27.740741,66.851852,3.637037

In [104]:
data1.groupby('country').gho.count().unique()

array([33])

In [105]:
dfnew = data1.drop_duplicates(subset=['country'], keep='first')
dfnew.groupby('region')[['beer_servings', 'wine_servings', 'spirit_servings', 'total_litres_of_pure_alcohol']].mean()

,beer_servings,wine_servings,spirit_servings,total_litres_of_pure_alcohol
region,,,,
Africa,68.826087,18.000000,17.304348,3.360870
Americas,155.600000,37.514286,148.257143,6.102857
Eastern Mediterranean,10.428571,4.857143,21.190476,0.714286
Europe,175.132075,123.528302,130.415094,7.873585
South_East Asia,14.818182,0.454545,44.090909,1.063636
Western Pacific,81.962963,27.740741,66.851852,3.637037

Заметим, что несмотря на удаление дубликатов среднее значение не меняется в силу того, что количество повторений стран в датасете одинаковое (по 33).

### 16

Создание новых признаков (feature engineering) является одним из основных средств улучшения качества работы алгоритмов машинного обучения на этапе обработки данных, а также отличный способ увеличить глубину ваших выводов из проделанного анализа в целом! Частично мы с вами уже осуществляли feature engineering, когда добавляли новые столбцы в задании 13 данного раздела.

Теперь давайте добавим в таблицу столбец, который будет показывать, какое общее количество servings per person производится в среднем по стране, к которой относится научная статья. Столбец для этого признака назовите 'total_servings'.

Чем может быть полезен такой признак?

***Бонус (2 бон. балла):*** Придумайте еще какой-нибудь свой осмысленный признак, который может быть полезен для анализа (несет в себе какую-то информацию), и добавьте его в таблицу. Обязательно аргументируйте, чем полезен ваш признак.

In [106]:
data1['total_servings'] = data1['beer_servings'] + data1['wine_servings'] + data1['spirit_servings']

Для более наглядного представления добавила столбец с разностью между минимальным значением по данной стране и статье и продолжительностью жизни, также отношение потребления алкоголя в стране к максимальному потреблению по всем странам. Ранк с потреблением алкоголя от минимального к максимальному и количество алкоголя на порцию, где сразу же заполнила nan-ы нулями.

In [107]:
data1['difference_with_min'] = data1['Numeric'] - data1['min_life_expectancy']
data1['total_alco_proportion'] = data1['total_litres_of_pure_alcohol'] / data['total_litres_of_pure_alcohol'].max()
data1['alco_per_serving'] = data1['total_litres_of_pure_alcohol'] / data1['total_servings']
data1['alco_consumption_rank'] = data1['total_litres_of_pure_alcohol'].rank(method='dense')
data1.fillna(0, inplace=True)

In [108]:
data1.sort_values('alco_consumption_rank').head()

,gho,year,region,income,country,sex,DisplayValue,Numeric,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,avg_life_expectancy,min_life_expectancy,total_servings,difference_with_min,total_alco_proportion,alco_per_serving,alco_consumption_rank
3201,Life expectancy at age 60 (years),2013,Europe,High_income,San Marino,Female,26,25.60971,0,0,0,0.0,24.098443,20.0,0,5.60971,0.0,0.0,1.0
5445,Healthy life expectancy (HALE) at birth (years),2013,Eastern Mediterranean,Low_income,Somalia,Male,45,45.40000,0,0,0,0.0,44.644444,42.0,0,3.40000,0.0,0.0,1.0
5446,Life expectancy at birth (years),2000,Eastern Mediterranean,Low_income,Somalia,Both sexes,50,50.00000,0,0,0,0.0,51.274240,45.0,0,5.00000,0.0,0.0,1.0
5447,Life expectancy at birth (years),2000,Eastern Mediterranean,Low_income,Somalia,Male,49,49.00000,0,0,0,0.0,51.274240,45.0,0,4.00000,0.0,0.0,1.0
5448,Healthy life expectancy (HALE) at birth (years),2012,Eastern Mediterranean,Low_income,Somalia,Both sexes,45,44.90000,0,0,0,0.0,44.644444,42.0,0,2.90000,0.0,0.0,1.0

### 17

Есть ли в данных категориальные признаки, которые принимают значения строк, а не чисел? Если да, то для многих алгоритмов это может стать серьезным препятствием, поэтому закодируйте категориальные признаки так, чтобы к данным можно было применить любые алгоритмы. Аргументируйте выбор методов кодирования.

*Подсказка. Вам могут помочь Label encoding и One-Hot Encoding. Но будьте внимательны! У каждого из этих методов есть свои сильные и слабые стороны, а также ограничения применимости.*

С помощью LabelEncoder-а можно заменить значения колонки со странами, тк их довольно много - 193, чтобы не плодить лишние колонки, а также сделаем то же самое с регионом, поскольку их довольно много также.

In [109]:
data1.sort_values('income').income.unique()

array(['High_income', 'Low_income', 'Lower_middle_income',
       'Upper_middle_income'], dtype=object)

In [110]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [111]:
country_t = le.fit_transform(data1['country'])

In [112]:
le.classes_

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia-Herzegovina', 'Botswana', 'Brazil', 'Brunei',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia',
       'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'Chile',
       'China', 'Colombia', 'Comoros', 'Congo', 'Cook Islands',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus',
       'Czech Republic', 'DR Congo', 'Denmark', 'Djibouti', 'Dominica',
       'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Fiji',
       'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany',
       'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hungary',
       'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland',
       'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan',
       'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia',
       'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Lithuania',
       'Luxembourg', 'Macedonia', 'Madagascar', 'Malawi', 'Malaysia',
       'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania',
       'Mauritius', 'Mexico', 'Micronesia', 'Moldova', 'Monaco',
       'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'North Korea', 'Norway',
       'Oman', 'Pakistan', 'Palau', 'Panama', 'Papua New Guinea',
       'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar',
       'Romania', 'Russian Federation', 'Rwanda', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Korea',
       'Spain', 'Sri Lanka', 'St. Kitts and Nevis', 'St. Lucia',
       'St. Vincent and the Grenadines', 'Sudan', 'Suriname', 'Swaziland',
       'Sweden', 'Switzerland', 'Syria', 'Tajikistan', 'Tanzania',
       'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago',
       'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'USA', 'Uganda',
       'Ukraine', 'United Arab Emirates', 'United Kingdom', 'Uruguay',
       'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam', 'Yemen', 'Zambia',
       'Zimbabwe'], dtype=object)

In [113]:
country_t

array([123, 123, 123, ...,  16,  16,  16])

In [114]:
data1['country'] = country_t

In [115]:
le1 = LabelEncoder()
regions = le1.fit_transform(data1['region'])
data1['region'] = regions

In [116]:
le1.classes_

array(['Africa', 'Americas', 'Eastern Mediterranean', 'Europe',
       'South_East Asia', 'Western Pacific'], dtype=object)

In [117]:
regions

array([1, 1, 1, ..., 3, 3, 3])

Поскольку в label encoder неудобно менять значения и упорядочивать их самостоятельно, то заменим значения по возрастанию уровня дохода самостоятельно (так как признаков не так уж и много, то это можно сделать вручную, иначе бы можно было отсортировать).

In [118]:
data1.income = data1.income.replace(['Low_income', 'Lower_middle_income', 'Upper_middle_income', 'High_income'], [1, 2, 3, 4])

Поскольку категорий в признаках gho и sex всего по 3, то их можно сделать one-hot кодированием не слишком увеличив размер датасета. Помимо этого, уберем одну из трех образовавшихся колонок у признаков, так тогда понятно, например,  что если у признаков женщина и мужчина 0, то рассматриваются оба пола одновременно. Подобный метод в машинном обучении это поможет справиться с переобучением.

In [119]:
data1 = pd.get_dummies(data1, columns=['gho', 'sex'], drop_first=True)
data1.head()

,year,region,income,country,DisplayValue,Numeric,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,...,min_life_expectancy,total_servings,difference_with_min,total_alco_proportion,alco_per_serving,alco_consumption_rank,gho_Life expectancy at age 60 (years),gho_Life expectancy at birth (years),sex_Female,sex_Male
0,1990,1,2,123,68,68.0,78,118,1,3.5,...,68.0,197,0.0,0.243056,0.017766,30.0,0,1,0,1
1,2013,1,2,123,62,61.9,78,118,1,3.5,...,60.9,197,1.0,0.243056,0.017766,30.0,0,0,0,1
2,1990,1,2,123,74,74.0,78,118,1,3.5,...,68.0,197,6.0,0.243056,0.017766,30.0,0,1,1,0
3,2000,1,2,123,76,76.0,78,118,1,3.5,...,68.0,197,8.0,0.243056,0.017766,30.0,0,1,1,0
4,2000,1,2,123,70,70.0,78,118,1,3.5,...,68.0,197,2.0,0.243056,0.017766,30.0,0,1,0,1

In [120]:
data1.shape

(6369, 21)

### 18

Придумайте какое-нибудь своё интересное задание на анализ предлагаемых данных и решите его.

Креативность в этом задании приветствуется, и за нее можно получить ***1-2 бонусных балла***!

*Подсказка. Вы можете вдохновляться различными заданиями из этого ДЗ, как, например, заданиями: 4, 6, 10, 12, 14, 15, 16. Но, чтобы получить бонусные баллы, лучше не используйте аналогичные идеи, а придумайте что-то своё!*

Проанализировать рост/падение среднего значения продолжительности жизни с течением времени для каждого из регионов.

In [121]:
data1.groupby(['region', 'year']).Numeric.mean().to_frame()

               Numeric
region year
0      1990  34.260870
       2000  37.663527
       2012  42.357246
       2013  42.742802
1      1990  44.728571
       2000  51.866349
       2012  53.553333
       2013  53.584629
2      1990  40.968254
       2000  48.066138
       2012  50.211640
       2013  50.687083
3      1990  45.871069
       2000  52.902096
       2012  55.288260
       2013  55.435319
4      1990  38.075758
       2000  45.716162
       2012  49.812121
       2013  50.070851
5      1990  42.148148
       2000  49.799177
       2012  52.335802
       2013  52.498923

Можем заметить, что есть тренд на рост средней продолжительности жизни.

Вычислить среднее значение дохода и уровня потребления алкоголя каждого вида и общего кол-ва алкоголя для каждого типа дохода и провести сравнительную аналитику.

In [122]:
data1.groupby('income')[['Numeric', 'wine_servings', 'beer_servings', 'spirit_servings', 'total_litres_of_pure_alcohol']].mean()

,Numeric,wine_servings,beer_servings,spirit_servings,total_litres_of_pure_alcohol
income,,,,,
1,40.675610,5.863636,28.977273,26.159091,2.243182
2,46.387936,14.603774,64.056604,66.943396,2.983019
3,50.462899,47.311111,169.333333,130.555556,6.393333
4,54.612445,125.156863,160.764706,99.176471,7.174510

И потребление алкоголя, и средний уровень жизни растет с увеличением дохода.

## Бонусная часть на анализ целевой переменной (до 5 бонусных баллов)

После всего проделанного анализа и подготовки данных мы можем перейти непосредственно к ответу на исходный вопрос исследования, который был сформулирован вами в задании 3 данного раздела.

### 19

***Бонус (5 бон. баллов):*** Дайте развернутый, обоснованный, подкрепленный данными и написанным вами кодом ответ на вопрос, влияют ли признаки зависимой таблицы на целевую переменную из главной таблицы и, если да, то каким именно образом влияют?

Обязательно аргументируйте полученные вами результаты и выводы. Чем подробнее и обоснованнее анализ вы проведете в рамках данного бонусного задания, тем больше бонусных баллов получите! Вы можете использовать подходы и методы из рассмотренных на семинаре и в рамках данного домашнего задания, а можете придумать и что-то своё. Креативность максимально приветствуется!



1.   Сначала сделаем корелляционный анализ признаков относительно целевой переменной.

In [123]:
data1[['wine_servings', 'beer_servings', 'spirit_servings', 'total_litres_of_pure_alcohol', 'Numeric']].corr()

,wine_servings,beer_servings,spirit_servings,total_litres_of_pure_alcohol,Numeric
wine_servings,1.000000,0.527172,0.194797,0.667598,0.129527
beer_servings,0.527172,1.000000,0.458819,0.835839,0.124204
spirit_servings,0.194797,0.458819,1.000000,0.654968,0.099499
total_litres_of_pure_alcohol,0.667598,0.835839,0.654968,1.000000,0.112060
Numeric,0.129527,0.124204,0.099499,0.112060,1.000000

In [124]:
data1.columns

Index(['year', 'region', 'income', 'country', 'DisplayValue', 'Numeric',
       'beer_servings', 'spirit_servings', 'wine_servings',
       'total_litres_of_pure_alcohol', 'avg_life_expectancy',
       'min_life_expectancy', 'total_servings', 'difference_with_min',
       'total_alco_proportion', 'alco_per_serving', 'alco_consumption_rank',
       'gho_Life expectancy at age 60 (years)',
       'gho_Life expectancy at birth (years)', 'sex_Female', 'sex_Male'],
      dtype='object')

Получим, что корелляция с целевой переменной довольно низкая, все же около 0, поэтому можно первоначально сделать вывод, что целевая переменная не зависит от них.

2. Посмотрим с точки зрения обучения простейшей модели регресии то, насколько сильно влияют данные признаки относительно других и насколько сильной будет ошибка. Посмотрим на коэффициенты после обучения модели.

In [125]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

#Избавились от лишних колонок, которые не будут использоваться в модели и "создают шум" при обучении
data_lg = data1.drop(columns=['DisplayValue', 'difference_with_min', 'total_alco_proportion',
                              'alco_consumption_rank', 'alco_per_serving', 'avg_life_expectancy', 'min_life_expectancy', 'total_servings'])

X = data_lg.drop(['Numeric'], axis=1)
y =data_lg['Numeric']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [126]:
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 25.42026665180478

In [127]:
coefficients = pd.DataFrame({'feature': X.columns, 'coefficient': model.coef_})
coefficients

                                  feature  coefficient
0                                    year     0.193610
1                                  region     0.940566
2                                  income     3.551381
3                                 country     0.004538
4                           beer_servings     0.018846
5                         spirit_servings     0.019842
6                           wine_servings     0.018094
7            total_litres_of_pure_alcohol    -0.863846
8   gho_Life expectancy at age 60 (years)   -40.623625
9    gho_Life expectancy at birth (years)     9.103745
10                             sex_Female     1.698520
11                               sex_Male    -1.789893

Видим, что коэффициенты при обучении меньше 1 по модулю на рассматриваемые категории из сопутсвующей таблицы, тогда можем сделать вывод, что они не так сильно влияют. Одними из самых влиятельных признаков будут типы статьи, а также уровень дохода в стране. Что неудивительно, поскольку тип дохода изменяет возраст от которого начинается отсчет и изменяет выборку, а также и итоговое значение переменной. А также основой для благоприятной жизни является наличие высокого дохода, который зачаствую обеспечивает наиболее благоприятные исходы для страны.
Итого - данные из прикрепленной к целевой таблице таблицы не являются релевантными и требуют аналогичной проработки по статьям, полу, году и другим данным, а поэтому влияния алкоголяь на уровень жизни практически не оказывает.